import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowDownToLine, BarChart3, Building2, CheckCircle2, ChevronRight, CircleHelp, Database, Download, FileJson, FileText, LayoutDashboard, Menu, RefreshCw, Search, Settings, ShieldCheck, X } from 'lucide-react';
import { BusinessConfig, TallyVoucher } from './types/gst';
import { autoFetchFromTally } from './utils/tallyLiveConnector';

const DEFAULT: BusinessConfig = { supplierGstin:'', tradeName:'', legalName:'', financialYear:'2026-27', returnPeriod:'082026', stateCode:'27', grossTurnoverPreviousYear:0 };
const fmt=(n:number)=>`₹${Math.round(n||0).toLocaleString('en-IN')}`;
const d=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('-'):s;

function makeJson(vs:TallyVoucher[],c:BusinessConfig){
  const b2cl:any[]=[]; const b2cs=new Map<string,any>(); const hsn=new Map<string,any>(); const groups=new Map<string,any>(); let total=0;
  const m=/^(\d{2})(\d{4})$/.exec(c.returnPeriod); const month=m?+m[1]:1,year=m?+m[2]:1970; const limit=year>2024||(year===2024&&month>=8)?100000:250000;
  for(const v of vs){
    total+=v.totalValue; const gst=(v.partyGstin||'').toUpperCase();
    if(gst.length===15){const g=groups.get(gst)||{ctin:gst,partyName:v.partyName,inv:[]};g.inv.push({inum:v.voucherNo,idt:d(v.date),val:v.totalValue,pos:v.pos,rchrg:v.isReverseCharge?'Y':'N',inv_typ:'R',itms:v.items.map((x,i)=>({num:i+1,itm_det:{rt:x.gstRate,txval:x.taxableAmount,iamt:x.igstAmount,camt:x.cgstAmount,samt:x.sgstAmount,csamt:x.cessAmount||0}}))});groups.set(gst,g);continue;}
    if(v.pos!==c.stateCode&&v.totalValue>limit){let g=b2cl.find(x=>x.pos===v.pos);if(!g){g={pos:v.pos,inv:[]};b2cl.push(g)}g.inv.push({inum:v.voucherNo,idt:d(v.date),val:v.totalValue,itms:v.items.map((x,i)=>({num:i+1,itm_det:{rt:x.gstRate,txval:x.taxableAmount,iamt:x.igstAmount,csamt:x.cessAmount||0}}))});continue;}
    for(const x of v.items){const k=`${v.pos!==c.stateCode?'INTER':'INTRA'}|${v.pos}|${x.gstRate}`;const z=b2cs.get(k)||{sply_ty:v.pos!==c.stateCode?'INTER':'INTRA',pos:v.pos,rt:x.gstRate,txval:0,iamt:0,camt:0,samt:0,csamt:0};z.txval+=x.taxableAmount;z.iamt+=x.igstAmount;z.camt+=x.cgstAmount;z.samt+=x.sgstAmount;z.csamt+=x.cessAmount||0;b2cs.set(k,z);const hk=`${x.hsnCode}|${x.unit}|${x.gstRate}`;const h=hsn.get(hk)||{num:0,hsn_sc:x.hsnCode,desc:x.itemName,uqc:x.unit,qty:0,val:0,txval:0,iamt:0,camt:0,samt:0,csamt:0};h.qty+=x.quantity;h.txval+=x.taxableAmount;h.iamt+=x.igstAmount;h.camt+=x.cgstAmount;h.samt+=x.sgstAmount;h.csamt+=x.cessAmount||0;h.val=h.txval+h.iamt+h.camt+h.samt+h.csamt;hsn.set(hk,h)}
  }
  const j:any={gstin:c.supplierGstin,fp:c.returnPeriod,gt:c.grossTurnoverPreviousYear,cur_gt:total,version:'GST3.0.4',hash:''};
  if(groups.size)j.b2b=[...groups.values()]; if(b2cl.length)j.b2cl=b2cl; if(b2cs.size)j.b2cs=[...b2cs.values()]; if(hsn.size)j.hsn={data:[...hsn.values()].map((x,i)=>({...x,num:i+1}))}; return j;
}

export default function Gstr1App(){
  const [c,setC]=useState<BusinessConfig>(()=>{try{return JSON.parse(localStorage.getItem('gstr1_config')||'null')||DEFAULT}catch{return DEFAULT}});
  const [vs,setVs]=useState<TallyVoucher[]>(()=>{try{return JSON.parse(localStorage.getItem('gstr1_vouchers')||'[]')}catch{return []}});
  const [q,setQ]=useState(''); const [settings,setSettings]=useState(false); const [syncing,setSyncing]=useState(false); const [status,setStatus]=useState('Connecting to your live TallyPrime company…'); const [ok,setOk]=useState(false); const [mobileNav,setMobileNav]=useState(false);
  useEffect(()=>localStorage.setItem('gstr1_config',JSON.stringify(c)),[c]); useEffect(()=>localStorage.setItem('gstr1_vouchers',JSON.stringify(vs)),[vs]);
  const sync=async()=>{setSyncing(true);setStatus('Reading the currently-open company from TallyPrime…');setOk(false);try{const r=await autoFetchFromTally('http://127.0.0.1:9000',c.stateCode);if(!r.success)throw new Error(r.message);if(r.result?.vouchers?.length)setVs(r.result.vouchers);const p=r.company||r.result?.companyProfile;if(p)setC(prev=>({...prev,...(p.gstin?{supplierGstin:p.gstin,stateCode:p.gstin.slice(0,2)}:{}),...(p.name?{tradeName:p.name,legalName:p.name}:{}),...(p.address?{companyAddress:p.address}:{}),...(p.stateName?{companyStateName:p.stateName}:{}),...(p.phone?{companyPhone:p.phone}:{}),...(p.email?{companyEmail:p.email}:{}),...(p.pincode?{companyPincode:p.pincode}:{})}));setStatus(r.message);setOk(true)}catch(e:any){setStatus(e?.message||'Unable to connect to TallyPrime. Please check port 9000.');setOk(false)}finally{setSyncing(false)}};
  useEffect(()=>{sync()},[]);
  const data=useMemo(()=>makeJson(vs,c),[vs,c]); const filtered=vs.filter(v=>`${v.voucherNo} ${v.partyName} ${v.partyGstin||''} ${v.pos}`.toLowerCase().includes(q.toLowerCase()));
  const totals=useMemo(()=>({taxable:vs.reduce((a,v)=>a+v.taxableValue,0),tax:vs.reduce((a,v)=>a+v.igst+v.cgst+v.sgst,0),value:vs.reduce((a,v)=>a+v.totalValue,0),b2b:vs.filter(v=>(v.partyGstin||'').length===15).length}),[vs]);
  const download=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`GSTR1_${c.supplierGstin||'TALLY'}_${c.returnPeriod}.json`;a.click();URL.revokeObjectURL(u)};
  const nav=[['Dashboard',LayoutDashboard],['Sales invoices',FileText],['GSTR-1 JSON',FileJson],['Company profile',Building2]] as const;
  return <div className="gstr-shell min-h-screen flex text-slate-900">
    <aside className="gstr-sidebar hidden lg:flex w-64 shrink-0 text-white flex-col fixed inset-y-0 left-0 z-30">
      <div className="h-20 px-6 flex items-center border-b border-white/10"><div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center mr-3 shadow-lg shadow-blue-900/30"><BarChart3 className="w-5 h-5"/></div><div><div className="font-bold tracking-tight">ANISH<span className="text-blue-400">TECH</span></div><div className="text-[10px] text-slate-400 tracking-[.18em] uppercase">Tax Intelligence</div></div></div>
      <div className="px-4 pt-6 pb-2 text-[10px] font-bold text-slate-500 uppercase tracking-[.18em]">Workspace</div>
      <nav className="px-3 space-y-1">{nav.map(([label,Icon],i)=><button key={label} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm ${i===0?'gstr-nav-active text-white':'text-slate-400 hover:text-white hover:bg-white/5'}`}><Icon className="w-4 h-4"/><span>{label}</span>{i===0&&<ChevronRight className="w-3.5 h-3.5 ml-auto text-slate-500"/>}</button>)}</nav>
      <div className="px-4 pt-7 pb-2 text-[10px] font-bold text-slate-500 uppercase tracking-[.18em]">System</div>
      <nav className="px-3 space-y-1"><button onClick={()=>setSettings(true)} className="w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm text-slate-400 hover:text-white hover:bg-white/5"><Settings className="w-4 h-4"/>Settings</button><button className="w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm text-slate-400 hover:text-white hover:bg-white/5"><CircleHelp className="w-4 h-4"/>Help centre</button></nav>
      <div className="mt-auto p-4"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="flex items-center gap-2 text-xs font-semibold"><ShieldCheck className="w-4 h-4 text-emerald-400"/> Secure workspace</div><p className="mt-2 text-[11px] leading-5 text-slate-500">Live Tally data is read through the configured bridge.</p></div><div className="mt-4 text-[10px] text-slate-600">ANISH TECHNOLOGIES • GSTR-1</div></div>
    </aside>
    <div className="flex-1 lg:ml-64 min-w-0">
      <header className="sticky top-0 z-20 bg-white/90 backdrop-blur-xl border-b border-slate-200/80"><div className="h-20 px-4 sm:px-6 lg:px-8 flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0"><button onClick={()=>setMobileNav(true)} className="lg:hidden p-2 rounded-lg hover:bg-slate-100"><Menu className="w-5 h-5"/></button><div className="min-w-0"><div className="text-[11px] font-bold text-blue-600 uppercase tracking-[.16em]">GSTR-1 Control Centre</div><h1 className="text-lg sm:text-xl font-bold truncate">Outward Supplies</h1></div></div><div className="flex items-center gap-2 sm:gap-3"><div className="hidden sm:flex items-center gap-2 px-3 py-2 rounded-full border border-slate-200 bg-slate-50 text-xs font-semibold"><span className={`w-2 h-2 rounded-full ${ok?'bg-emerald-500':'bg-amber-500'}`}></span>{ok?'Tally connected':'Sync required'}</div><button onClick={sync} disabled={syncing} className="inline-flex items-center gap-2 px-3 sm:px-4 py-2.5 rounded-xl border border-slate-200 bg-white text-xs sm:text-sm font-semibold hover:border-blue-300 hover:shadow-sm disabled:opacity-60"><RefreshCw className={`w-4 h-4 ${syncing?'animate-spin':''}`}/><span className="hidden sm:inline">Sync Tally</span></button><button onClick={download} className="inline-flex items-center gap-2 px-3 sm:px-4 py-2.5 rounded-xl bg-blue-600 text-white text-xs sm:text-sm font-semibold shadow-lg shadow-blue-600/20 hover:bg-blue-700"><Download className="w-4 h-4"/><span className="hidden sm:inline">Export JSON</span></button><button onClick={()=>setSettings(true)} className="p-2.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50"><Settings className="w-4 h-4"/></button></div></div></header>
      <main className="max-w-[1500px] mx-auto px-4 sm:px-6 lg:px-8 py-7 space-y-6">
        <div className={`gstr-card rounded-2xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 ${ok?'':'border-amber-200'}`}><div className="flex items-start gap-3"><div className={`mt-0.5 p-2 rounded-xl ${ok?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}>{ok?<CheckCircle2 className="w-5 h-5"/>:<AlertCircle className="w-5 h-5"/>}</div><div><div className="text-sm font-semibold">{ok?'Live TallyPrime connection active':'TallyPrime connection status'}</div><div className="text-xs text-slate-500 mt-1">{status}</div></div></div><div className="text-xs text-slate-400 font-medium">Last action: live sync</div></div>
        <section className="gstr-card rounded-3xl overflow-hidden"><div className="p-6 sm:p-7 bg-gradient-to-r from-slate-950 via-slate-900 to-blue-950 text-white"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6"><div><div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-white/10 border border-white/10 text-[10px] font-bold uppercase tracking-widest text-blue-200"><Building2 className="w-3.5 h-3.5"/> Current Tally company</div><h2 className="mt-4 text-2xl sm:text-3xl font-bold tracking-tight">{c.tradeName||'Waiting for Tally company…'}</h2><p className="mt-2 text-sm text-slate-300 max-w-2xl">{c.companyAddress||'Company address will appear automatically after live sync.'}{c.companyPincode?`, ${c.companyPincode}`:''}</p></div><div className="lg:text-right"><div className="text-[10px] uppercase tracking-widest text-slate-400">GSTIN</div><div className="mt-1 text-lg font-mono font-semibold tracking-wide">{c.supplierGstin||'—'}</div><div className="mt-2 text-xs text-slate-400">{c.companyStateName||'State'} • FY {c.financialYear} • Period {c.returnPeriod}</div></div></div></div><div className="grid sm:grid-cols-3 divide-y sm:divide-y-0 sm:divide-x divide-slate-200 bg-white"><div className="p-5"><div className="text-[10px] uppercase tracking-widest font-bold text-slate-400">Phone</div><div className="mt-1 text-sm font-semibold">{c.companyPhone||'—'}</div></div><div className="p-5"><div className="text-[10px] uppercase tracking-widest font-bold text-slate-400">Email</div><div className="mt-1 text-sm font-semibold truncate">{c.companyEmail||'—'}</div></div><div className="p-5"><div className="text-[10px] uppercase tracking-widest font-bold text-slate-400">Legal entity</div><div className="mt-1 text-sm font-semibold truncate">{c.legalName||c.tradeName||'—'}</div></div></div></section>
        <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><div className="gstr-card rounded-2xl p-5"><div className="flex justify-between"><span className="text-xs font-semibold text-slate-500">Sales invoices</span><span className="p-2 rounded-xl bg-blue-50 text-blue-600"><FileText className="w-4 h-4"/></span></div><div className="mt-5 text-2xl font-bold">{vs.length.toLocaleString('en-IN')}</div><div className="mt-1 text-xs text-slate-400">Live vouchers imported</div></div><div className="gstr-card rounded-2xl p-5"><div className="flex justify-between"><span className="text-xs font-semibold text-slate-500">Taxable value</span><span className="p-2 rounded-xl bg-violet-50 text-violet-600"><BarChart3 className="w-4 h-4"/></span></div><div className="mt-5 text-2xl font-bold">{fmt(totals.taxable)}</div><div className="mt-1 text-xs text-slate-400">Before GST</div></div><div className="gstr-card rounded-2xl p-5"><div className="flex justify-between"><span className="text-xs font-semibold text-slate-500">Output tax</span><span className="p-2 rounded-xl bg-amber-50 text-amber-600"><Database className="w-4 h-4"/></span></div><div className="mt-5 text-2xl font-bold">{fmt(totals.tax)}</div><div className="mt-1 text-xs text-slate-400">IGST + CGST + SGST</div></div><div className="gstr-card rounded-2xl p-5"><div className="flex justify-between"><span className="text-xs font-semibold text-slate-500">Invoice value</span><span className="p-2 rounded-xl bg-emerald-50 text-emerald-600"><ArrowDownToLine className="w-4 h-4"/></span></div><div className="mt-5 text-2xl font-bold">{fmt(totals.value)}</div><div className="mt-1 text-xs text-slate-400">B2B invoices: {totals.b2b}</div></div></section>
        <section className="gstr-card rounded-2xl overflow-hidden"><div className="p-5 sm:p-6 border-b border-slate-200 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="font-bold text-base">Live sales register</h3><span className="px-2 py-1 rounded-full bg-blue-50 text-blue-700 text-[10px] font-bold uppercase tracking-wide">TallyPrime</span></div><p className="mt-1 text-xs text-slate-500">Invoices fetched from the currently-open Tally company</p></div><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoice, party or GSTIN" className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-slate-200 bg-slate-50 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></div></div><div className="overflow-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50/90"><tr>{['Invoice','Date','Customer','GSTIN','Place of supply','Taxable value','Invoice value'].map((x,i)=><th key={x} className={`px-5 py-3.5 text-left text-[10px] uppercase tracking-wider font-bold text-slate-500 ${i>4?'text-right':''}`}>{x}</th>)}</tr></thead><tbody>{filtered.length?filtered.map(v=><tr key={v.id} className="gstr-table-row border-t border-slate-100"><td className="px-5 py-4 font-bold text-slate-900">{v.voucherNo}</td><td className="px-5 py-4 text-slate-500">{v.date}</td><td className="px-5 py-4"><div className="font-semibold">{v.partyName||'—'}</div><div className="text-[10px] text-slate-400 mt-0.5">{v.isReverseCharge?'Reverse charge':''}</div></td><td className="px-5 py-4 font-mono text-xs text-slate-500">{v.partyGstin||'Unregistered'}</td><td className="px-5 py-4"><span className="px-2 py-1 rounded-lg bg-slate-100 text-xs font-semibold">{v.posName||v.pos||'—'}</span></td><td className="px-5 py-4 text-right font-medium">{fmt(v.taxableValue)}</td><td className="px-5 py-4 text-right font-bold">{fmt(v.totalValue)}</td></tr>):<tr><td colSpan={7} className="px-6 py-16 text-center"><div className="mx-auto w-12 h-12 rounded-2xl bg-slate-100 flex items-center justify-center"><FileText className="w-5 h-5 text-slate-400"/></div><div className="mt-3 font-semibold">No live invoices found</div><div className="mt-1 text-xs text-slate-500">Keep TallyPrime open on the required company and use Sync Tally.</div></td></tr>}</tbody></table></div><div className="px-5 py-4 border-t border-slate-200 bg-slate-50/60 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs text-slate-500"><span>Showing {filtered.length} of {vs.length} invoices</span><button onClick={download} className="inline-flex items-center gap-2 font-semibold text-blue-600 hover:text-blue-700"><ArrowDownToLine className="w-3.5 h-3.5"/> Download GSTR-1 JSON <ChevronRight className="w-3 h-3"/></button></div></section>
      </main>
      <footer className="px-4 sm:px-8 py-7 border-t border-slate-200 text-xs text-slate-400 flex flex-col sm:flex-row justify-between gap-2"><span>ANISH TECHNOLOGIES • GSTR-1 AUTOMATION PLATFORM</span><span>Live Tally bridge • Secure data flow</span></footer>
    </div>
    {mobileNav&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-slate-950/60" onClick={()=>setMobileNav(false)}></div><div className="absolute left-0 top-0 bottom-0 w-72 gstr-sidebar text-white p-4 shadow-2xl"><div className="flex items-center justify-between p-2"><div className="font-bold">ANISH<span className="text-blue-400">TECH</span></div><button onClick={()=>setMobileNav(false)}><X className="w-5 h-5"/></button></div><div className="mt-8 space-y-1">{nav.map(([label,Icon],i)=><button key={label} onClick={()=>setMobileNav(false)} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm ${i===0?'gstr-nav-active':'text-slate-400'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div></div></div>}
    {settings&&<div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-xl bg-white rounded-3xl shadow-2xl overflow-hidden"><div className="p-6 border-b border-slate-200 flex items-center justify-between"><div><h2 className="font-bold text-lg">GSTR-1 workspace settings</h2><p className="text-xs text-slate-500 mt-1">Review return configuration</p></div><button onClick={()=>setSettings(false)} className="p-2 rounded-xl hover:bg-slate-100"><X className="w-5 h-5"/></button></div><div className="p-6 grid sm:grid-cols-2 gap-4">{(['supplierGstin','tradeName','legalName','financialYear','returnPeriod','stateCode'] as const).map(k=><label className="text-xs font-bold text-slate-500" key={k}>{k==='supplierGstin'?'GSTIN':k==='tradeName'?'Trade name':k==='legalName'?'Legal name':k==='financialYear'?'Financial year':k==='returnPeriod'?'Return period':'State code'}<input className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" value={String(c[k])} onChange={e=>setC({...c,[k]:e.target.value})}/></label>)}</div><div className="p-6 bg-slate-50 border-t border-slate-200 flex justify-end gap-2"><button onClick={()=>setSettings(false)} className="px-4 py-2.5 rounded-xl border border-slate-200 bg-white text-sm font-semibold">Cancel</button><button onClick={()=>setSettings(false)} className="px-5 py-2.5 rounded-xl bg-blue-600 text-white text-sm font-semibold">Save changes</button></div></div></div>}
  </div>;
}
