import { useEffect, useMemo, useState } from 'react';
import { Download, RefreshCw, Settings, CheckCircle2, AlertCircle } from 'lucide-react';
import { BusinessConfig, TallyVoucher } from './types/gst';
import { autoFetchFromTally } from './utils/tallyLiveConnector';

const DEFAULT: BusinessConfig = { supplierGstin:'', tradeName:'', legalName:'', financialYear:'2026-27', returnPeriod:'082026', stateCode:'27', grossTurnoverPreviousYear:0 };
const fmt=(n:number)=>`₹${Math.round(n||0).toLocaleString('en-IN')}`;
const d=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('-'):s;

function makeJson(vs:TallyVoucher[],c:BusinessConfig){
  const b2cl:any[]=[]; const b2cs=new Map<string,any>(); const hsn=new Map<string,any>(); const groups=new Map<string,any>(); let total=0;
  const m=/^(\d{2})(\d{4})$/.exec(c.returnPeriod); const month=m?+m[1]:1,year=m?+m[2]:1970; const limit=year>2024||(year===2024&&month>=8)?100000:250000;
  for(const v of vs){
    total+=v.totalValue; const gst=(v.partyGstin||'').toUpperCase();
    if(gst.length===15){const g=groups.get(gst)||{ctin:gst,partyName:v.partyName,inv:[]};g.inv.push({inum:v.voucherNo,idt:d(v.date),val:v.totalValue,pos:v.pos,rchrg:v.isReverseCharge?'Y':'N',inv_typ:'R',itms:v.items.map((x,i)=>({num:i+1,itm_det:{rt:x.gstRate,txval:x.taxableAmount,iamt:x.igstAmount,camt:x.cgstAmount,samt:x.sgstAmount,csamt:x.cessAmount||0}}))});groups.set(gst,g);continue;}
    if(v.pos!==c.stateCode&&v.totalValue>limit){let g=b2cl.find(x=>x.pos===v.pos);if(!g){g={pos:v.pos,inv:[]};b2cl.push(g)}g.inv.push({inum:v.voucherNo,idt:d(v.date),val:v.totalValue,itms:v.items.map((x,i)=>({num:i+1,itm_det:{rt:x.gstRate,txval:x.taxableAmount,iamt:x.igstAmount,csamt:x.cessAmount||0}}))});continue;}
    for(const x of v.items){const k=`${v.pos!==c.stateCode?'INTER':'INTRA'}|${v.pos}|${x.gstRate}`;const z=b2cs.get(k)||{sply_ty:v.pos!==c.stateCode?'INTER':'INTRA',pos:v.pos,rt:x.gstRate,txval:0,iamt:0,camt:0,samt:0,csamt:0};z.txval+=x.taxableAmount;z.iamt+=x.igstAmount;z.camt+=x.cgstAmount;z.samt+=x.sgstAmount;z.csamt+=x.cessAmount||0;b2cs.set(k,z);const hk=`${x.hsnCode}|${x.unit}|${x.gstRate}`;const h=hsn.get(hk)||{num:0,hsn_sc:x.hsnCode,desc:x.itemName,uqc:x.unit,qty:0,val:0,txval:0,iamt:0,camt:0,samt:0,csamt:0};h.qty+=x.quantity;h.txval+=x.taxableAmount;h.iamt+=x.igstAmount;h.camt+=x.cgstAmount;h.samt+=x.sgstAmount;h.csamt+=x.cessAmount||0;h.val=h.txval+h.iamt+h.camt+h.samt+h.csamt;hsn.set(hk,h)}
  }
  const j:any={gstin:c.supplierGstin,fp:c.returnPeriod,gt:c.grossTurnoverPreviousYear,cur_gt:total,version:'GST3.0.4',hash:''};
  if(groups.size)j.b2b=[...groups.values()]; if(b2cl.length)j.b2cl=b2cl; if(b2cs.size)j.b2cs=[...b2cs.values()]; if(hsn.size)j.hsn={data:[...hsn.values()].map((x,i)=>({...x,num:i+1}))}; return j;
}

export default function Gstr1App(){
  const [c,setC]=useState<BusinessConfig>(()=>{try{return JSON.parse(localStorage.getItem('gstr1_config')||'null')||DEFAULT}catch{return DEFAULT}});
  const [vs,setVs]=useState<TallyVoucher[]>(()=>{try{return JSON.parse(localStorage.getItem('gstr1_vouchers')||'[]')}catch{return []}});
  const [q,setQ]=useState(''); const [settings,setSettings]=useState(false); const [syncing,setSyncing]=useState(false); const [status,setStatus]=useState('TallyPrime se live data connect ho raha hai...'); const [ok,setOk]=useState(false);
  useEffect(()=>localStorage.setItem('gstr1_config',JSON.stringify(c)),[c]); useEffect(()=>localStorage.setItem('gstr1_vouchers',JSON.stringify(vs)),[vs]);
  const sync=async()=>{setSyncing(true);setStatus('TallyPrime ki currently-open company read ho rahi hai...');setOk(false);try{const r=await autoFetchFromTally('http://127.0.0.1:9000',c.stateCode);if(!r.success)throw new Error(r.message);if(r.result?.vouchers?.length)setVs(r.result.vouchers);const p=r.company||r.result?.companyProfile;if(p)setC(prev=>({...prev,...(p.gstin?{supplierGstin:p.gstin,stateCode:p.gstin.slice(0,2)}:{}),...(p.name?{tradeName:p.name,legalName:p.name}:{}),...(p.address?{companyAddress:p.address}:{}),...(p.stateName?{companyStateName:p.stateName}:{}),...(p.phone?{companyPhone:p.phone}:{}),...(p.email?{companyEmail:p.email}:{}),...(p.pincode?{companyPincode:p.pincode}:{})}));setStatus(r.message);setOk(true)}catch(e:any){setStatus(e?.message||'Tally connection failed. Port 9000 check karein.');setOk(false)}finally{setSyncing(false)}};
  useEffect(()=>{sync()},[]);
  const data=useMemo(()=>makeJson(vs,c),[vs,c]); const filtered=vs.filter(v=>`${v.voucherNo} ${v.partyName} ${v.partyGstin||''}`.toLowerCase().includes(q.toLowerCase()));
  const download=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`GSTR1_${c.supplierGstin||'TALLY'}_${c.returnPeriod}.json`;a.click();URL.revokeObjectURL(u)};
  return <div className="min-h-screen bg-slate-100 text-slate-900"><header className="bg-slate-950 text-white p-4"><div className="max-w-7xl mx-auto flex justify-between items-center gap-3"><div><h1 className="text-xl font-bold">Tally → GSTR-1</h1><p className="text-xs text-slate-300">Live TallyPrime company • GSTIN, address and Sales vouchers</p></div><div className="flex gap-2"><button onClick={sync} disabled={syncing} className="px-3 py-2 bg-slate-800 rounded-lg text-sm"><RefreshCw className={`inline w-4 h-4 mr-1 ${syncing?'animate-spin':''}`}/>Sync Tally</button><button onClick={()=>setSettings(true)} className="p-2 bg-slate-800 rounded-lg"><Settings className="w-4 h-4"/></button><button onClick={download} className="px-3 py-2 bg-emerald-600 rounded-lg text-sm"><Download className="inline w-4 h-4 mr-1"/>Download GSTR-1</button></div></div></header>
  <main className="max-w-7xl mx-auto p-4 space-y-4"><div className={`border rounded-xl p-3 bg-white flex items-center gap-2 text-sm ${ok?'border-emerald-200':'border-amber-200'}`}>{ok?<CheckCircle2 className="w-5 h-5 text-emerald-600"/>:<AlertCircle className="w-5 h-5 text-amber-600"/>}<span>{status}</span></div>
  <section className="bg-white border rounded-xl p-4"><div className="grid md:grid-cols-3 gap-4"><div><div className="text-xs text-slate-500">Current Tally Company</div><b>{c.tradeName||'—'}</b></div><div><div className="text-xs text-slate-500">GSTIN</div><b className="font-mono">{c.supplierGstin||'—'}</b></div><div><div className="text-xs text-slate-500">State</div><b>{c.companyStateName||c.stateCode||'—'}</b></div></div>{(c.companyAddress||c.companyPhone||c.companyEmail||c.companyPincode)&&<div className="mt-3 pt-3 border-t text-sm text-slate-700"><b>Address:</b> {c.companyAddress||'—'}{c.companyPincode?`, ${c.companyPincode}`:''}{c.companyPhone?` • ${c.companyPhone}`:''}{c.companyEmail?` • ${c.companyEmail}`:''}</div>}</section>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Invoices',vs.length],['Taxable',fmt(vs.reduce((a,v)=>a+v.taxableValue,0))],['Tax',fmt(vs.reduce((a,v)=>a+v.igst+v.cgst+v.sgst,0))],['Value',fmt(vs.reduce((a,v)=>a+v.totalValue,0))]].map(x=><div className="bg-white border rounded-xl p-4" key={String(x[0])}><div className="text-xs text-slate-500">{x[0]}</div><b className="text-lg">{x[1]}</b></div>)}</div>
  <div className="bg-white border rounded-xl overflow-hidden"><div className="p-3 border-b flex justify-between"><b>Live Tally Sales Vouchers</b><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoice / party / GSTIN" className="border rounded-lg px-3 py-1.5 text-sm"/></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{['Invoice','Date','Party','GSTIN','POS','Taxable','Total'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(v=><tr className="border-t" key={v.id}><td className="p-3 font-semibold">{v.voucherNo}</td><td className="p-3">{v.date}</td><td className="p-3">{v.partyName}</td><td className="p-3 font-mono text-xs">{v.partyGstin||'—'}</td><td className="p-3">{v.pos}</td><td className="p-3 text-right">{fmt(v.taxableValue)}</td><td className="p-3 text-right font-semibold">{fmt(v.totalValue)}</td></tr>)}</tbody></table></div></div>
  </main>{settings&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-xl p-5 w-full max-w-lg"><h2 className="font-bold mb-4">GSTR-1 Settings</h2>{(['supplierGstin','tradeName','legalName','financialYear','returnPeriod','stateCode'] as const).map(k=><label className="block text-xs font-semibold mb-3" key={k}>{k}<input className="mt-1 w-full border rounded-lg p-2" value={String(c[k])} onChange={e=>setC({...c,[k]:e.target.value})}/></label>)}<button onClick={()=>setSettings(false)} className="w-full bg-emerald-600 text-white rounded-lg p-2">Save</button></div></div>}</div>}
